### PR TITLE
sentMail on signup,forgotPassword, updateEmail, updatePassword

### PR DESCRIPTION
**Pull request by Anujraval24**

### CODE REVIEW

**Comment by Anujraval24** [comment]
[sentMail on signup,forgotPassword, updateEmail, updatePassword](https://trello.com/c/Tyw9uuQR/8-sentmail-on-signupforgotpassword-updateemail-updatepassword)

**Comment by ankitvadariya** [comment]
.vscode should be in gitignore

**Comment by Anujraval24** [comment]
> .vscode should be in gitignore

ya

**Comment by Anujraval24** [comment]
> .vscode should be in gitignore

I will fix this soon

**Comment by Anujraval24** [comment]
[Handled Errors and fixed bugs](https://trello.com/c/uZRwE3JF/9-handled-errors-and-fixed-bugs)

**Comment by Anujraval24** [comment]
[subscription fixed](https://trello.com/c/HIvtJqDi/16-subscription-fixed)

**Pull request closed without merging**
